version: 2.1

orbs:
  maven: circleci/maven@0.0.12
- run:
      - mkdir /home/circleci/project/target/surefire-reports
workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
